### ISSUE TITLE
Implement `Astra++` interface

### ISSUE THREAD

**Issue by sekaiking** [sekaiking/bos-workspace#2]
In an effort to streamline the development process, team members are encouraged to create issues for the components/screens they are working on. This ensures that everyone has a clear understanding of what is being worked on and avoids duplication of effort.

- When a Screen or a Component is ready for deployment let's merge it into the main branch.

- Since the API isn't ready, you can create mock data that resembles the expected data from the indexer.

- The designs for Astra++ are available on [Figma](https://www.figma.com/file/oA41se1TnBuFe2AC71jguw/Astra%2B%2B-%7C-NEAR?type=design&node-id=3%3A3&mode=design&t=EuLmCtMYD2980Gjc-1).

## Components

When choosing a screen to work on, if you identify a common component that will be shared across other screens, please do it separately by first linking an issue here.

- [ ] [`issue`]() - [Proposal Card]()
- [ ] [`issue`]() - [DAO Card]()
- [ ] [`issue`]() - [DAO Layout](https://www.figma.com/file/oA41se1TnBuFe2AC71jguw/Astra%2B%2B-%7C-NEAR?type=design&node-id=861-29147&mode=design&t=bm8U9HNgLr5pp1OX-4)

## Screens

- [ ] [`issue`]() - [Home > Social Feed](https://www.figma.com/file/oA41se1TnBuFe2AC71jguw/Astra%2B%2B-%7C-NEAR?type=design&node-id=757-26923&mode=design&t=bm8U9HNgLr5pp1OX-4) (NOT ready for implementation)
- [ ] [`issue`]() - [Home > My Proposals](https://www.figma.com/file/oA41se1TnBuFe2AC71jguw/Astra%2B%2B-%7C-NEAR?type=design&node-id=741-23436&mode=design&t=bm8U9HNgLr5pp1OX-4) (NOT ready for implementation)
- [ ] [`issue`]() - [DAOs > NDC Governance](https://www.figma.com/file/oA41se1TnBuFe2AC71jguw/Astra%2B%2B-%7C-NEAR?type=design&node-id=623-11075&mode=design&t=bm8U9HNgLr5pp1OX-4) (NOT ready for implementation)
- [ ] [`issue`]() - [DAOs > Following](https://www.figma.com/file/oA41se1TnBuFe2AC71jguw/Astra%2B%2B-%7C-NEAR?type=design&node-id=1124-28689&mode=design&t=bm8U9HNgLr5pp1OX-4)
- [ ] [`issue`]() - [DAOs > All](https://www.figma.com/file/oA41se1TnBuFe2AC71jguw/Astra%2B%2B-%7C-NEAR?type=design&node-id=106-3217&mode=design&t=bm8U9HNgLr5pp1OX-4)
- [ ] [`issue`]() - [Bounties](https://www.figma.com/file/oA41se1TnBuFe2AC71jguw/Astra%2B%2B-%7C-NEAR?type=design&node-id=638-9084&mode=design&t=bm8U9HNgLr5pp1OX-4)
- [ ] [`issue`]() - [Actions library](https://www.figma.com/file/oA41se1TnBuFe2AC71jguw/Astra%2B%2B-%7C-NEAR?type=design&node-id=652-12973&mode=design&t=bm8U9HNgLr5pp1OX-4)
- [ ] [`issue`]() - [Create DAO](https://www.figma.com/file/oA41se1TnBuFe2AC71jguw/Astra%2B%2B-%7C-NEAR?type=design&node-id=538-5484&mode=design&t=bm8U9HNgLr5pp1OX-4)
- [ ] [`issue`]() - [DAO > Discussion]() (Design is missing)
- [ ] [`issue`]() - [DAO > Proposals - Card view](https://www.figma.com/file/oA41se1TnBuFe2AC71jguw/Astra%2B%2B-%7C-NEAR?type=design&node-id=861-29148&mode=design&t=bm8U9HNgLr5pp1OX-4)
- [ ] [`issue`]() - [DAO > Proposals - Table view](https://www.figma.com/file/oA41se1TnBuFe2AC71jguw/Astra%2B%2B-%7C-NEAR?type=design&node-id=876-62424&mode=design&t=bm8U9HNgLr5pp1OX-4)
- [ ] [`issue`]() - [DAO > Fund Flow](https://www.figma.com/file/oA41se1TnBuFe2AC71jguw/Astra%2B%2B-%7C-NEAR?type=design&node-id=861-29147&mode=design&t=bm8U9HNgLr5pp1OX-4)
- [ ] [`issue`]() - [DAO > Members & Policy](https://www.figma.com/file/oA41se1TnBuFe2AC71jguw/Astra%2B%2B-%7C-NEAR?type=design&node-id=931-22040&mode=design&t=bm8U9HNgLr5pp1OX-4)
- [ ] [`issue`]() - [DAO > Voting History](https://www.figma.com/file/oA41se1TnBuFe2AC71jguw/Astra%2B%2B-%7C-NEAR?type=design&node-id=931-22041&mode=design&t=bm8U9HNgLr5pp1OX-4)
- [ ] [`issue`]() - [DAO > Inter House](https://www.figma.com/file/oA41se1TnBuFe2AC71jguw/Astra%2B%2B-%7C-NEAR?type=design&node-id=915-49316&mode=design&t=bm8U9HNgLr5pp1OX-4)
- [ ] [`issue`]() - [DAO > Settings](https://www.figma.com/file/oA41se1TnBuFe2AC71jguw/Astra%2B%2B-%7C-NEAR?type=design&node-id=931-22039&mode=design&t=bm8U9HNgLr5pp1OX-4)
- [ ] [`issue`]() - [DAO > Bounties]() (Design is missing)

## General Issues

Any bugs than need fixing or changes requested by other team members should be linked here
